title: Raghav Balasankaran
email: raghavbalasankaran@gmail.com
description: >-
  Developer blog. Writing about code, systems, and things I'm learning.
baseurl: ""
url: "https://sbraghav.github.io"
twitter_username: SB_Raghav
github_username: sbraghav
linkedin_username: raghav-balasankaran
permalink: /:title

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  tags:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: []
